const gulp = require("gulp");
const { browserSync, BrowserSyncConfig } = require("./browsersync");
const { sassCompileStyle, sassCompileBuild, sassCompileTinyMCE, sassCompileAdmin, sassCompileWooCommerce } = require("./sass");
const { tailwindCompile } = require("./tailwind");
const { iconfont: icons } = require("./icons");
const PhpTasks = require("./php");
const { copyImages } = require("./images");
const { jsCompile, adminJsCompile, TinyMceJsCompile } = require("./js.js");
const { copyJson } = require("./json");

const assetsFolder = "./src/assets";

function watch() {
	browserSync.init(BrowserSyncConfig);

	// --- SASS WATCHERS (Unchanged) ---
	gulp.watch(`${assetsFolder}/scss/styles/**/*.scss`, gulp.series(sassCompileStyle));
	gulp.watch(`${assetsFolder}/scss/builds/**/*.scss`, gulp.series(sassCompileBuild));
	gulp.watch(`${assetsFolder}/scss/tinymces/**/*.scss`, gulp.series(sassCompileTinyMCE));
	gulp.watch(`${assetsFolder}/scss/admins/**/*.scss`, gulp.series(sassCompileAdmin));
	gulp.watch(`${assetsFolder}/scss/woocommerces/**/*.scss`, gulp.series(sassCompileWooCommerce));

	// --- TAILWIND WATCHER (Correct) ---
	// This watches for changes that require CSS to be re-generated by Tailwind.
	gulp.watch(
		['./tailwind.config.js', './src/**/*.php', `${assetsFolder}/scss/tailwind.scss`],
		gulp.series(tailwindCompile)
	);

	// --- JAVASCRIPT WATCHER (Correct) ---
	// This watches for changes in your JS files, including Flowbite imports.
	gulp.watch(`${assetsFolder}/js/**/*.js`, gulp.series(jsCompile, adminJsCompile, TinyMceJsCompile));

	// --- ASSET WATCHERS (Unchanged) ---
	gulp.watch(`${assetsFolder}/images/**/*.+(jpg|jpeg|png|gif|svg|webp|ico)`, gulp.series(copyImages));
	gulp.watch(`${assetsFolder}/icons/*.svg`, gulp.series(icons));
	gulp.watch("./src/json/**/*.json", gulp.series(copyJson));

	// =========================================================================
	// --- CORRECTED PHP WATCHERS (This is the fix) ---
	// These lines are restored from your original file. They call the specific
	// tasks in `php.js` to COPY the changed files to the `/build` directory.
	// =========================================================================
	gulp.watch(["./src/Classes/**/*.php"], gulp.series(PhpTasks.PhpWatch.Classes)).on('change', browserSync.reload);
	gulp.watch(["./src/functions/**/*.php"], gulp.series(PhpTasks.PhpWatch.Functions)).on('change', browserSync.reload);
	gulp.watch(["./src/components/**/*.php"], gulp.series(PhpTasks.PhpWatch.Components)).on('change', browserSync.reload);
	gulp.watch(["./src/woocommerce/**/*.php"], gulp.series(PhpTasks.PhpWatch.WooCommerce)).on('change', browserSync.reload);
	gulp.watch(["./src/*.php", "!./src/vendor/**/*"], gulp.series(PhpTasks.PhpWatch.MainFiles)).on('change', browserSync.reload);

	// This final watcher is a fallback for any CSS changes that don't get streamed.
	gulp.watch("./build/css/**/*.css").on("change", browserSync.reload);
}

module.exports = watch;
gulp.task("watch", gulp.series(watch));